feature: add setting config design
halo-dev/rfcs pull request #17
Opened 2022-07-06 07:26 UTC by guqing

### What this PR does?
新增主题和插件配置设计
- 通过 yaml 生成表单
- 通过表单改变主题或插件的运行参数

/cc @halo-dev/sig-docs 

```release-note
None
```

2022-07-06 10:23 UTC, wangzhen-fit2cloud commented on setting/README.md
> +ConfigMap 并不提供保密或者加密功能。
说到这个，是否还需要提供 `secret` 的设计呢？

2022-07-06 10:48 UTC, guqing commented on setting/README.md
> +ConfigMap 并不提供保密或者加密功能。
> 说到这个，是否还需要提供 `secret` 的设计呢？

目前暂不需要，用到的时候在设计吧

2022-07-11 07:50 UTC, JohnNiang reviewed
如果 ConfigMap 设计来源于 Kubernetes，建议贴上参考链接。

2022-07-11 07:53 UTC, guqing commented
> 如果 ConfigMap 设计来源于 Kubernetes，建议贴上参考链接。

ok

2022-07-11 14:00 UTC, JohnNiang commented
> > 如果 ConfigMap 设计来源于 Kubernetes，建议贴上参考链接。
> 
> ok

建议把参考链接放到 RFC 中。

2022-07-11 14:22 UTC, guqing commented
> > > > 如果 ConfigMap 设计来源于 Kubernetes，建议贴上参考链接。
> > > 
> > > 
> > > ok
> > 
> > 
> > 建议把参考链接放到 RFC 中。
> 
> 在RFC内容中关于ConfigMap描述那段具有一个链接，需要在明确一下吗

已补充

2022-07-12 03:07 UTC, JohnNiang requested changes

2022-07-12 03:07 UTC, JohnNiang commented on setting/README.md
> +  name: plugin-setting-${GENERATE_ID}
建议在 Setting 上引入 ConfigMap 的名称，可以放在 Spec 中，也可以放在 Label 中。

2022-07-12 03:07 UTC, JohnNiang commented on setting/README.md
> +apiVersion: core.halo.run/v1alpha1
这里的组名应该为：`theme.halo.run` 吧。

2022-07-12 03:07 UTC, JohnNiang commented on setting/README.md
> +apiVersion: core.halo.run/v1alpha1
同上。

2022-07-12 03:27 UTC, guqing commented on setting/README.md
> +apiVersion: core.halo.run/v1alpha1
> 这里的组名应该为：`theme.halo.run` 吧。

插件也要用，直接用theme.halo.run不太好，那把group改为空吧为core提供的公共自定义模型

2022-07-12 03:58 UTC, JohnNiang requested changes

2022-07-12 03:58 UTC, JohnNiang commented on setting/README.md
> +    theme.halo.run/configmap-name: CONFIG_MAP_NAME
```suggestion
    halo.run/configmap-name: CONFIG_MAP_NAME
```

2022-07-12 03:58 UTC, JohnNiang commented on setting/README.md
> +    theme.halo.run/theme-name: THEME_NAME
建议移除不需要的 Labels。

2022-07-12 03:58 UTC, JohnNiang commented on setting/README.md
> +    plugin.halo.run/plugin-name: PLUGIN_NAME
同上。

2022-07-12 03:58 UTC, JohnNiang commented on setting/README.md
> +    plugin.halo.run/configmap-name: CONFIG_MAP_NAME
```suggestion
    halo.run/configmap-name: CONFIG_MAP_NAME
```

2022-07-12 04:25 UTC, guqing commented on setting/README.md
> +    theme.halo.run/configmap-name: CONFIG_MAP_NAME
> 

当插件后端需要获取值时需要查询 ConfigMap 而不需要先去查询 Setting 来得到 ConfigMap name再查，因此会将关联关系直接保存到 Theme 自定义模型中

2022-07-12 04:27 UTC, guqing commented on setting/README.md
> +    theme.halo.run/configmap-name: CONFIG_MAP_NAME
https://github.com/halo-dev/rfcs/pull/17/files#diff-ddf034c05892e2c4ec35f395b3520172b39d1cf306a185d1322d6cf2cb5aeaedR190-R193

2022-07-12 06:22 UTC, JohnNiang approved these changes
/kind feature
/approve

2022-07-12 07:02 UTC, ruibaby reviewed
/lgtm

2022-07-12 07:03 UTC, merged