feat: Add RFC template
halo-dev/rfcs pull request #4
Opened 2022-03-15 03:22 UTC by guqing

### What this PR does?
提供一个供任何人在创作新 RFC 时使用的基本模板。 
- RFC 模板通常由几个基本部分组成：提议的变更摘要、概述变更为何重要的动机或问题陈述、变更可能导致的潜在缺陷列表以及设计部分和实施细节。
- 模板的每个部分都包含指导性问题，以帮助 RFC 的作者批判性地思考他们提出的变更、它为何重要、它可能复杂的地方以及它可能影响谁或什么。

### Why we need it?
规范RFC写作格式

2022-03-15 03:24 UTC, ruibaby requested changes

2022-03-15 03:24 UTC, ruibaby commented on template.md
> +| **状态**   | WIP \|  In-Review \| Approved \| Obsolete  |
状态是否可以使用 tag 来标记

2022-03-15 03:29 UTC, guqing commented on template.md
> +| **状态**   | WIP \|  In-Review \| Approved \| Obsolete  |
该状态无法使用github tag标记 而是表示这个RFC的具体实现的进行状态 例如RFC的实现是否在进行中或审查中或被作废

2022-03-15 03:34 UTC, guqing commented on template.md
> +| **状态**   | WIP \|  In-Review \| Approved \| Obsolete  |
当一个RFC的PR被确定为要实施则会被合并，但此时社区并不知道该RFC的进行状态，所以当一个RFC在进行中或已完成时需要修改该状态来让社区知道

2022-03-18 02:45 UTC, JohnNiang reviewed
是否需要对文件名的格式有要求，比如：

001-xxx.md
002-yyy.md

2022-03-18 02:52 UTC, guqing commented
> 是否需要对文件名的格式有要求，比如：
> 
> 001-xxx.md 002-yyy.md
可以有

2022-03-18 03:33 UTC, ruibaby commented
> 可以有，但无法在该模版中描述

放在 readme 吧。

2022-03-18 03:34 UTC, guqing commented
> > 可以有，但无法在该模版中描述
> 
> 放在 readme 吧。

可以

2022-03-18 03:39 UTC, JohnNiang reviewed
建议在 README.md 中添加引用这个模板的链接。

2022-03-18 08:18 UTC, JohnNiang approved these changes

2022-03-19 10:58 UTC, ruibaby approved these changes

2022-03-19 10:58 UTC, merged